### ISSUE TITLE
Box Containers Alignement

### ISSUE THREAD

**Issue by JhayD02** [FEU-TECH-Code-Igniter/WST---KeithNetic---Summative#3]
Fix Box Alignment 
![ss](https://github.com/user-attachments/assets/596631ab-99d1-4f07-9a52-3b06def459b0)

**Comment by LuisMaala** [comment]
Done.
![Screenshot 2024-11-20 092258](https://github.com/user-attachments/assets/040baf7c-6f5f-4f78-af8d-a11b3a562985)
